-- COLOSSEUM MODE v0.0.1
--[[
    COLOSSEUM MODE 
  Colosseum Base Tweakunits

  This file defines custom unit tweaks for the Colosseum game mode in BAR.
  It overrides the build options and properties for factories, constructors, and commanders,
  restricting them to mobile units from all factions and disabling reclaiming.
  Units evolve at the 5 minutes mark, and special rules are applied to support the custom game mode.

  Pair this with the other mode module for a complete Colosseum experience.
  - Colosseum Units Costs 

    This file is part of the BAR Colosseum mode for Spring RTS.

    by Giamme, Pandaro, Fra
    thanks to all BAR Italian community for testing and feedback
]]
{
    
    armdrag = { 
        reclaimable = false
    }, 
    armcom = {
        canReclaim = true,
        buildoptions = {
            [1] = "armlab",
            [2] = "corlab",
            [3] = "leglab",
            [4] = "corvp",
            [5] = "armvp",
            [6] = "legvp",
            [7] = "armap",
            [8] = "corap",
            [9] = "legap",
            [10] = "armhp",
            [11] = "corhp",
            [12] = "leghp",
            [13] = "armsy",
            [14] = "corsy",
            [15] = "legsy",
            [16] = "armalab",
            [17] = "coralab",
            [18] = "lagalab",
            [19] = "armavp",
            [20] = "coravp",
            [21] = "legavp",
            [22] = "armaap",
            [23] = "coraap",
            [24] = "legaap",
            [25] = "armfhp",
            [26] = "corfhp",
            [27] = "legfhp",
            [28] = "armamsub",
            [29] = "coramsub",
            [30] = "legamsub",
            [31] = "armplat",
            [32] = "corplat",
            [33] = "legplat",
            [34] = "armasy",
            [35] = "corasy",
            [36] = "legasy",
            [37] = "armshltx",
            [38] = "corshltx",
            [39] = "legshltx",
            [40] = "armshltxuw",
            [41] = "legshltxuw",
            [42] = "corshltxuw",
        }, 
        metalmake = 0,
        energymake = 0,
        energystorage = 20000,

    }, 
    corcom = {
        canReclaim = true,
        metalmake = 0,
        energymake = 0,
        energystorage = 20000,
        buildoptions = {
            [1] = "armlab",
            [2] = "corlab",
            [3] = "leglab",
            [4] = "corvp",
            [5] = "armvp",
            [6] = "legvp",
            [7] = "armap",
            [8] = "corap",
            [9] = "legap",
            [10] = "armhp",
            [11] = "corhp",
            [12] = "leghp",
            [13] = "armsy",
            [14] = "corsy",
            [15] = "legsy",
            [16] = "armalab",
            [17] = "coralab",
            [18] = "lagalab",
            [19] = "armavp",
            [20] = "coravp",
            [21] = "legavp",
            [22] = "armaap",
            [23] = "coraap",
            [24] = "legaap",
            [25] = "armfhp",
            [26] = "corfhp",
            [27] = "legfhp",
            [28] = "armamsub",
            [29] = "coramsub",
            [30] = "legamsub",
            [31] = "armplat",
            [32] = "corplat",
            [33] = "legplat",
            [34] = "armasy",
            [35] = "corasy",
            [36] = "legasy",
            [37] = "armshltx",
            [38] = "corshltx",
            [39] = "legshltx",
            [40] = "armshltxuw",
            [41] = "legshltxuw",
            [42] = "corshltxuw",
        }, 
    },

    legcom = {
        canReclaim = true,
        buildoptions = {
            [1] = "armlab",
            [2] = "corlab",
            [3] = "leglab",
            [4] = "corvp",
            [5] = "armvp",
            [6] = "legvp",
            [7] = "armap",
            [8] = "corap",
            [9] = "legap",
            [10] = "armhp",
            [11] = "corhp",
            [12] = "leghp",
            [13] = "armsy",
            [14] = "corsy",
            [15] = "legsy",
            [16] = "armalab",
            [17] = "coralab",
            [18] = "lagalab",
            [19] = "armavp",
            [20] = "coravp",
            [21] = "legavp",
            [22] = "armaap",
            [23] = "coraap",
            [24] = "legaap",
            [25] = "armfhp",
            [26] = "corfhp",
            [27] = "legfhp",
            [28] = "armamsub",
            [29] = "coramsub",
            [30] = "legamsub",
            [31] = "armplat",
            [32] = "corplat",
            [33] = "legplat",
            [34] = "armasy",
            [35] = "corasy",
            [36] = "legasy",
            [37] = "armshltx",
            [38] = "corshltx",
            [39] = "legshltx",
            [40] = "armshltxuw",
            [41] = "legshltxuw",
            [42] = "corshltxuw",
        }, 
        metalmake = 0,
        energymake = 0,
        energystorage = 20000,

    }, 

}


    